# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import my_service_pb2 as my__service__pb2


class MyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.topicModel = channel.stream_unary(
        '/MyService/topicModel',
        request_serializer=my__service__pb2.QueryRequest.SerializeToString,
        response_deserializer=my__service__pb2.QueryResponse.FromString,
        )


class MyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def topicModel(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'topicModel': grpc.stream_unary_rpc_method_handler(
          servicer.topicModel,
          request_deserializer=my__service__pb2.QueryRequest.FromString,
          response_serializer=my__service__pb2.QueryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
